# Install Docker and add user vagrant to docker group.

---
- name: Install Docker
  yum: name=docker state=present

- name: Install Docker Compose
  pip: 
    name: docker-compose 
    state: present

- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Add vagrant to Docker Group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Restart docker service
  service: name=docker enabled=yes state=restarted

- name: Run the Services Defined in docker-compose.yml.
  command: docker-compose -f /vagrant/environment/provisioning/docker-compose/docker-compose.yml up -d

#- name: Run the Services Defined in docker-compose.yml
#  docker_service:
#    project_src: /vagrant/environment/provisioning/docker-compose/
#    state: present