# Install Docker and add user vagrant to docker group.

---
- name: Install Docker
  yum: name=docker state=present

- name: Install Docker Compose
  pip: 
    name: docker-compose 
    state: present

- name: Create Docker Group
  group:
    name: docker
    state: present

- name: Add vagrant to Docker Group
  user:
    name: vagrant
    groups: docker
    append: yes
  notify: Restart docker service

- name: Run the Services Defined in docker-compose.yml
  docker_service:
    project_src: environment/provision/docker/