# Install all packages needed to run and develop with java.

---
- name: Install necessary packages for Java development
  yum: name={{ item }} state=installed
  with_items:
      - java-1.8.0-openjdk-devel
      - java-1.8.0-openjdk
      - maven