# Docker compose to have Zookeeper, Kafka, Kafka Manager, NiFi, ELK running for development.
# Provided by @Ziliotti
version: '3'

networks:
  proxy:
    external: true

services:
  zookeeper:
  image: confluent/zookeeper
  container_name: kafka_zookeeper
  ports:
    - "2181:2181"
  networks: 
    - proxy
    - default

  kafka:
    image: wurstmeister/kafka
    container_name: kafka-wurstmeister
    ports:
      - "9092:9092"    
    environment:
      - KAFKA_ADVERTISED_HOST_NAME
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_DELETE_TOPIC_ENABLE=true
      - KAFKA_LOG_RETENTION_HOURS=1
      - KAFKA_MESSAGE_MAX_BYTES=10000000
      - KAFKA_REPLICA_FETCH_MAX_BYTES=10000000
      - KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS=60000
      - KAFKA_NUM_PARTITIONS=2
      - KAFKA_DELETE_RETENTION_MS=1000
    networks: 
      - proxy
      - default
    depends_on: 
      - zookeeper

  kafka-manager:
    image: sheepkiller/kafka-manager
    container_name: kafka-manager
    ports:
      - "9000:9000"    
    environment:
      ZK_HOSTS: zookeeper:2181
      APPLICATION_SECRET: letmein
      KM_ARGS: -Djava.net.preferIPv4Stack=true
    networks: 
      - proxy
      - default
    depends_on: 
      - zookeeper
      - kafka
  
  nifi:
    image: docker pull apache/nifi
    container_name: nifi
    ports:
      - "9090:9090"    
    environment:
      - NIFI_WEB_HTTP_PORT='9090'
    networks: 
      - proxy
      - default

## ELK Stack
  elk:

  

