---
- name: Install EPEL repo
  yum: 
    name: epel-release 
    state: present

- name: Install basic packages and tools
  yum: name={{ item }} state=present
  with_items:
    - nss-mdns
    - net-tools
    - telnet
    - tcpdump
    - lsof
    - strace
    - mlocate
    - wget
    - curl
    - git
    - vim
    - python-setuptools
    - python-pip


- name: Install NTP
  yum:
    pkg: ntp
    state: installed

- name: Start NTP
  service: 
    name: ntpd
    enabled: yes 
    state: started
  #command: service ntpd start

- name: Sync clock with NTP server.
  command: sudo hwclock --systohc

#- name: Configure mDNS
#  lineinfile:
#    path: /etc/avahi/avahi-daemon.conf
#    regexp: '^#allow-interfaces=eth0'
#    line: 'allow-interfaces=eth1'
#    state: present
#    backrefs: yes
#  notify: Restart mDNS service 
