---
- name: Install SElinux ansible module dependencies
  yum: 
    name: libselinux-python 
    state: installed

- name: Disable SELinux in conf file
  selinux: 
    state: disabled

- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  service: 
    name: firewalld 
    enabled: no 
    state: stopped