---
- name: Install SElinux ansible module dependencies
  yum: 
    name: libselinux-python 
    state: installed

- name: Disable SELinux in /etc/selinux/config file
  selinux: 
    state: disabled

- name: Set SELinux to permissive
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  service: 
    name: firewalld 
    enabled: no 
    state: stopped


  
- name: Stop iptables
  command: service iptables stop

- name: Stop iptables6
  command: service ip6tables stop    
