---
- name: Install SElinux ansible module dependencies
  yum: 
    name: libselinux-python 
    state: installed

- name: Disable SELinux in /etc/selinux/config file at next reboot
  selinux: 
    state: disabled

- name: Set SELinux in permissive mode until the machine is rebooted
  selinux:
    policy: targeted
    state: permissive

- name: Disable firewalld
  service: 
    name: firewalld 
    enabled: no 
    state: stopped


- name: Change PasswordAuthentication in /etc/ssh/sshd_config
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication.*no'
    line: 'PasswordAuthentication yes'
  notify: Restart sshd service


#- name: Change PasswordAuthentication in /etc/ssh/sshd_config
#  shell: sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
#  become: yes
  
#- name: Restart sshd service
#  service: 
#    name: sshd
#    enabled: yes 
#    state: restarted